name: ktlint

on:
  pull_request:
    paths:
      - master
  push:
    branches:
      - !master

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"