name: Run Unit Tests

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/unit_tests.yml"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
