name: Verify PR

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/verify_pr.yml"

jobs:
  ktlint:
    name: Verify lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Run Lint on app module
          command: ./gradlew :app:lintDebug
          when: always
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebug
          when: always

  build_artifacts:
    name: Verify build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew clean :katmaps-library:build

  test:
    name: Verify unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results